name: mock-pipeline
log-level: debug
log-file: /Users/xuenqlve/log/kyogre
data-source: {}
metadata: {}
iquery: {}
pipelines:
  - name: mock-demo
    metadata:
      mock-meta:
        type: mock
        config:
          name: mock-meta
    generators:
      - name: mock-generator
        type: mock
        metadata-ref: mock-meta
        config:
          prefix: demo
    scenario:
      type: mock
      metadata-ref: mock-meta
      generators:
        - mock-generator
      config:
        message-count: 5
        interval-ms: 50
    pressure:
      type: mock
      config:
        name: mock-pressure
