name: mock-pipeline
log-level: debug
log-file: /Users/admin/log/kyogre
data-source: { }
metadata:
  mock-meta:
    type: mock
    config:
      name: mock-meta
      lookup-enabled: true
generator:
  mock-generator:
    type: mock
    config:
      prefix: demo
lookup:
  mock-lookup:
    type: memory
scenario:
  mock-scenario:
    type: mock
    lookup: mock-lookup
    metadata: mock-meta
    generators:
      - mock-generator
    config:
      message-count: 100
      interval-ms: 50
pressure:
  mock-pressure:
    type: mock
    config:
      name: mock-pressure
pipelines:
  - name: mock-demo
    scenario: mock-scenario
    pressure:
      - mock-pressure
